#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_define_op = 2,
  sym_semicolon = 3,
  sym_arrow_op = 4,
  sym_arrow_query_op = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  sym_slash = 9,
  sym_colon = 10,
  sym_star = 11,
  sym_cache_flag = 12,
  sym_force_flag = 13,
  sym_identifier = 14,
  sym_source_file = 15,
  sym_definition = 16,
  sym_track_line = 17,
  sym_flow = 18,
  sym_step = 19,
  sym_group = 20,
  sym_annotated_node = 21,
  sym_node_name = 22,
  sym_module_name = 23,
  sym_facilitator = 24,
  sym_label = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_track_line_repeat1 = 27,
  aux_sym_flow_repeat1 = 28,
  aux_sym_group_repeat1 = 29,
  aux_sym_annotated_node_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_define_op] = "define_op",
  [sym_semicolon] = "semicolon",
  [sym_arrow_op] = "arrow_op",
  [sym_arrow_query_op] = "arrow_query_op",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_slash] = "slash",
  [sym_colon] = "colon",
  [sym_star] = "star",
  [sym_cache_flag] = "cache_flag",
  [sym_force_flag] = "force_flag",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_track_line] = "track_line",
  [sym_flow] = "flow",
  [sym_step] = "step",
  [sym_group] = "group",
  [sym_annotated_node] = "annotated_node",
  [sym_node_name] = "node_name",
  [sym_module_name] = "module_name",
  [sym_facilitator] = "facilitator",
  [sym_label] = "label",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_track_line_repeat1] = "track_line_repeat1",
  [aux_sym_flow_repeat1] = "flow_repeat1",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym_annotated_node_repeat1] = "annotated_node_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_define_op] = sym_define_op,
  [sym_semicolon] = sym_semicolon,
  [sym_arrow_op] = sym_arrow_op,
  [sym_arrow_query_op] = sym_arrow_query_op,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_slash] = sym_slash,
  [sym_colon] = sym_colon,
  [sym_star] = sym_star,
  [sym_cache_flag] = sym_cache_flag,
  [sym_force_flag] = sym_force_flag,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_track_line] = sym_track_line,
  [sym_flow] = sym_flow,
  [sym_step] = sym_step,
  [sym_group] = sym_group,
  [sym_annotated_node] = sym_annotated_node,
  [sym_node_name] = sym_node_name,
  [sym_module_name] = sym_module_name,
  [sym_facilitator] = sym_facilitator,
  [sym_label] = sym_label,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_track_line_repeat1] = aux_sym_track_line_repeat1,
  [aux_sym_flow_repeat1] = aux_sym_flow_repeat1,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym_annotated_node_repeat1] = aux_sym_annotated_node_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_define_op] = {
    .visible = true,
    .named = true,
  },
  [sym_semicolon] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_op] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_query_op] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_slash] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_cache_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_force_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_track_line] = {
    .visible = true,
    .named = true,
  },
  [sym_flow] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated_node] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_module_name] = {
    .visible = true,
    .named = true,
  },
  [sym_facilitator] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_track_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotated_node_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_text, 1},
  [3] =
    {field_body, 2},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 16,
        '#', 15,
        '(', 9,
        ')', 11,
        '*', 14,
        ',', 10,
        '-', 1,
        '/', 12,
        ':', 13,
        ';', 6,
        '>', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 2:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_define_op);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_semicolon);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_arrow_op);
      if (lookahead == '?') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_arrow_query_op);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_slash);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_colon);
      if (lookahead == '=') ADVANCE(5);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_star);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_cache_flag);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_force_flag);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_define_op] = ACTIONS(1),
    [sym_semicolon] = ACTIONS(1),
    [sym_arrow_op] = ACTIONS(1),
    [sym_arrow_query_op] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_slash] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [sym_star] = ACTIONS(1),
    [sym_cache_flag] = ACTIONS(1),
    [sym_force_flag] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(33),
    [sym_definition] = STATE(10),
    [sym_track_line] = STATE(10),
    [sym_flow] = STATE(25),
    [sym_step] = STATE(13),
    [sym_group] = STATE(15),
    [sym_annotated_node] = STATE(15),
    [sym_node_name] = STATE(4),
    [sym_module_name] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [2] = {
    [sym_facilitator] = STATE(2),
    [sym_label] = STATE(2),
    [aux_sym_annotated_node_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
    [sym_semicolon] = ACTIONS(11),
    [sym_arrow_op] = ACTIONS(13),
    [sym_arrow_query_op] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(11),
    [sym_slash] = ACTIONS(15),
    [sym_colon] = ACTIONS(18),
    [sym_star] = ACTIONS(21),
    [sym_cache_flag] = ACTIONS(21),
    [sym_force_flag] = ACTIONS(21),
    [sym_identifier] = ACTIONS(11),
  },
  [3] = {
    [sym_facilitator] = STATE(2),
    [sym_label] = STATE(2),
    [aux_sym_annotated_node_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(24),
    [sym_comment] = ACTIONS(24),
    [sym_semicolon] = ACTIONS(24),
    [sym_arrow_op] = ACTIONS(26),
    [sym_arrow_query_op] = ACTIONS(24),
    [anon_sym_LPAREN] = ACTIONS(24),
    [anon_sym_COMMA] = ACTIONS(24),
    [anon_sym_RPAREN] = ACTIONS(24),
    [sym_slash] = ACTIONS(28),
    [sym_colon] = ACTIONS(30),
    [sym_star] = ACTIONS(32),
    [sym_cache_flag] = ACTIONS(32),
    [sym_force_flag] = ACTIONS(32),
    [sym_identifier] = ACTIONS(24),
  },
  [4] = {
    [sym_facilitator] = STATE(3),
    [sym_label] = STATE(3),
    [aux_sym_annotated_node_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(34),
    [sym_comment] = ACTIONS(34),
    [sym_semicolon] = ACTIONS(34),
    [sym_arrow_op] = ACTIONS(36),
    [sym_arrow_query_op] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(34),
    [anon_sym_COMMA] = ACTIONS(34),
    [anon_sym_RPAREN] = ACTIONS(34),
    [sym_slash] = ACTIONS(28),
    [sym_colon] = ACTIONS(30),
    [sym_star] = ACTIONS(38),
    [sym_cache_flag] = ACTIONS(38),
    [sym_force_flag] = ACTIONS(38),
    [sym_identifier] = ACTIONS(34),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(42), 1,
      sym_arrow_op,
    ACTIONS(40), 13,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_slash,
      sym_colon,
      sym_star,
      sym_cache_flag,
      sym_force_flag,
      sym_identifier,
  [19] = 2,
    ACTIONS(46), 1,
      sym_arrow_op,
    ACTIONS(44), 13,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_slash,
      sym_colon,
      sym_star,
      sym_cache_flag,
      sym_force_flag,
      sym_identifier,
  [38] = 2,
    ACTIONS(50), 1,
      sym_arrow_op,
    ACTIONS(48), 13,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_slash,
      sym_colon,
      sym_star,
      sym_cache_flag,
      sym_force_flag,
      sym_identifier,
  [57] = 3,
    ACTIONS(52), 1,
      sym_define_op,
    ACTIONS(42), 2,
      sym_arrow_op,
      sym_colon,
    ACTIONS(40), 10,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      sym_slash,
      sym_star,
      sym_cache_flag,
      sym_force_flag,
      sym_identifier,
  [77] = 10,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(25), 1,
      sym_flow,
    STATE(32), 1,
      sym_module_name,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
    STATE(9), 3,
      sym_definition,
      sym_track_line,
      aux_sym_source_file_repeat1,
  [111] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym_comment,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(25), 1,
      sym_flow,
    STATE(32), 1,
      sym_module_name,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
    STATE(9), 3,
      sym_definition,
      sym_track_line,
      aux_sym_source_file_repeat1,
  [145] = 4,
    ACTIONS(71), 1,
      sym_arrow_op,
    ACTIONS(73), 1,
      sym_arrow_query_op,
    STATE(12), 1,
      aux_sym_flow_repeat1,
    ACTIONS(69), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [164] = 4,
    ACTIONS(77), 1,
      sym_arrow_op,
    ACTIONS(80), 1,
      sym_arrow_query_op,
    STATE(12), 1,
      aux_sym_flow_repeat1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [183] = 4,
    ACTIONS(71), 1,
      sym_arrow_op,
    ACTIONS(73), 1,
      sym_arrow_query_op,
    STATE(11), 1,
      aux_sym_flow_repeat1,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [202] = 2,
    ACTIONS(87), 1,
      sym_arrow_op,
    ACTIONS(85), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [216] = 2,
    ACTIONS(91), 1,
      sym_arrow_op,
    ACTIONS(89), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [230] = 2,
    ACTIONS(95), 1,
      sym_arrow_op,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [244] = 2,
    ACTIONS(97), 1,
      sym_arrow_op,
    ACTIONS(75), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      sym_arrow_query_op,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [258] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(26), 1,
      sym_flow,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
  [278] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(28), 1,
      sym_flow,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
  [298] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(27), 1,
      sym_flow,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
  [318] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(13), 1,
      sym_step,
    STATE(31), 1,
      sym_flow,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
  [338] = 3,
    ACTIONS(103), 1,
      sym_semicolon,
    STATE(24), 1,
      aux_sym_track_line_repeat1,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_identifier,
  [351] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(4), 1,
      sym_node_name,
    STATE(17), 1,
      sym_step,
    STATE(15), 2,
      sym_group,
      sym_annotated_node,
  [368] = 3,
    ACTIONS(107), 1,
      sym_semicolon,
    STATE(24), 1,
      aux_sym_track_line_repeat1,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_identifier,
  [381] = 3,
    ACTIONS(103), 1,
      sym_semicolon,
    STATE(22), 1,
      aux_sym_track_line_repeat1,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_identifier,
  [394] = 1,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      sym_comment,
      sym_semicolon,
      anon_sym_LPAREN,
      sym_identifier,
  [402] = 1,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_identifier,
  [409] = 3,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_group_repeat1,
  [419] = 3,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_group_repeat1,
  [429] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_group_repeat1,
  [439] = 1,
    ACTIONS(123), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [444] = 1,
    ACTIONS(125), 1,
      sym_define_op,
  [448] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [452] = 1,
    ACTIONS(129), 1,
      sym_identifier,
  [456] = 1,
    ACTIONS(131), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 19,
  [SMALL_STATE(7)] = 38,
  [SMALL_STATE(8)] = 57,
  [SMALL_STATE(9)] = 77,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 145,
  [SMALL_STATE(12)] = 164,
  [SMALL_STATE(13)] = 183,
  [SMALL_STATE(14)] = 202,
  [SMALL_STATE(15)] = 216,
  [SMALL_STATE(16)] = 230,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 278,
  [SMALL_STATE(20)] = 298,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 338,
  [SMALL_STATE(23)] = 351,
  [SMALL_STATE(24)] = 368,
  [SMALL_STATE(25)] = 381,
  [SMALL_STATE(26)] = 394,
  [SMALL_STATE(27)] = 402,
  [SMALL_STATE(28)] = 409,
  [SMALL_STATE(29)] = 419,
  [SMALL_STATE(30)] = 429,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 444,
  [SMALL_STATE(33)] = 448,
  [SMALL_STATE(34)] = 452,
  [SMALL_STATE(35)] = 456,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_annotated_node_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_annotated_node_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotated_node_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotated_node_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotated_node_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated_node, 2, 0, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotated_node, 2, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated_node, 1, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotated_node, 1, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_name, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, 0, 3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_facilitator, 2, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_facilitator, 2, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_name, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_flow_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_flow_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_line, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_track_line_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_track_line_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_track_line, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_arrow(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
